# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Iconos unicode... 
# http://www.fileformat.info/info/unicode/category/So/list.htm
#
# ICONOS QUE FUNCIONAN EN EL TÃTULO DE LA PÃGINA:
# âœ“ Â® Â© â‰« â— âœ” âœ† â†’ â‡¨ã€ã€‘âŠ› ( )
# ðŸ¥‡ - Medalla
# ðŸ™‚ - Cara sonriente
# âœ… - Check fondo verde (puede variar)
# ðŸ˜ - Cara con corazones
# â™»ï¸ - Reciclar
# âœ‚ï¸ - Tijeras
# ðŸ¤“ - Cara con gafas
# ðŸ¤‘ - Cara con dÃ³lar ojos
# ðŸ”¥ - Llamas
# ðŸ’¥ - ExplosiÃ³n
#
# ICONOS QUE FUNCIONAN EN META-DESCRIPCIÃ“N:
#
# ðŸ¤– - Cabeza de robot
# ðŸ’¼ - MaletÃ­n
# âœ“
# Â®
# Â©
# âœ
# â‰«
# â—
# âœ… - Check fondo verde
# â›”
# âŒ - cruz roja
# âœ¨ - Estrellas
# ðŸ˜‚
# ðŸ”¥ - Llamas
# âœ”
# âœ†
# â›³ - Hoyo golf
# âœŒï¸
# ðŸ‘Œ -
# ðŸ™Œ - Dos manos stop
# â¤ï¸
# âš ï¸
# âš¡
# ðŸš€ - Cohete
# â†’
# â‡¨
# âž•
# âŒ› - Reloj arena
# â›” -
# â˜
# âŒš - Reloj
# â­ - Estrella
# âž¡ï¸
# â­ - Estrella



# Site settings
title: La mejor âœ… informaciÃ³n sobre pulseras de actividad y fitness ðŸ¥‡.
email: web@pulseradeactividad.info
description: >
  Reviews y anÃ¡lisis veraces de las âœ¨ mejores pulseras de actividad, fitness, y pulsÃ³metros deportivos âŒš.
  ðŸš€ Las opiniones mÃ¡s valiosas, consejos y comparativas. ðŸš€ Descubre como pueden
  ayudarte a mejorar tu forma fÃ­sica .
logo: "/assets/logo.png"
logo_amp: "/assets/logo-amp.png"
logo_amp__width: 176
logo_amp__height: 60
logo_16x9: "/assets/logo-16x9.png"
logo_4x3: "/assets/logo-4x3.png"
logo_1x1: "/assets/logo-1x1.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pulseradeactividad.info" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'PulseraDeActividad.info'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"
twitter_username: jekyllrb
github_username:  jekyll

collections:
  paginas:
    output: true
    permalink: /:path.html

  historias:
    output: true
    permalink: /historias/:path.html

exclude:
  - 'README*.md'
  - 'Gemfile*'
  - 'LICENSE'
  - 'vendor'
  - '*.orig'
  - 'feed.xml'
  - 'resources'

# Google Analytics
analytics_id: "UA-158375791-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

# https://github.com/jekyll/jekyll-feed
feed:
  path: atom.xml
  excerpt_only: true

plugins:
  - jekyll-paginate
  - jekyll-feed

sass:
  style: compressed
