# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#
# Iconos unicode...
# http://www.fileformat.info/info/unicode/category/So/list.htm
#
# âŒš watch:            http://www.fileformat.info/info/unicode/char/231a/index.htm
# â© flechas derecha:  http://www.fileformat.info/info/unicode/char/23e9/index.htm
# â° alarma reloj:     http://www.fileformat.info/info/unicode/char/23f0/index.htm
# â± cronometro:       http://www.fileformat.info/info/unicode/char/23f1/index.htm
# ðŸ” top:              http://www.fileformat.info/info/unicode/char/1f51d/index.htm
# â­ star:             http://www.fileformat.info/info/unicode/char/2b50/index.htm
# ðŸ†š VS:               http://www.fileformat.info/info/unicode/char/1f19a/index.htm
# ðŸŒŸ glowing star:     http://www.fileformat.info/info/unicode/char/1f31f/index.htm
# ðŸŽ– medalla (militar):http://www.fileformat.info/info/unicode/char/1f396/index.htm
# ðŸƒ runner:           http://www.fileformat.info/info/unicode/char/1f3c3/index.htm
# ðŸ… medalla:          http://www.fileformat.info/info/unicode/char/1f3c5/index.htm
# ðŸ† trofeo:           http://www.fileformat.info/info/unicode/char/1f3c6/index.htm
# ðŸŠ nadar:            http://www.fileformat.info/info/unicode/char/1f3ca/index.htm
# ðŸ‹ pesas:            http://www.fileformat.info/info/unicode/char/1f3cb/index.htm
# ðŸ‘ mano ok:            http://www.fileformat.info/info/unicode/char/1f44d/index.htm
# ðŸ‘Ž mano ko:            http://www.fileformat.info/info/unicode/char/1f44e/index.htm
# ðŸ‘ aplausos:           http://www.fileformat.info/info/unicode/char/1f44f/index.htm
# corona:             http://www.fileformat.info/info/unicode/char/1f451/index.htm
# ðŸ‘“ gafas:             http://www.fileformat.info/info/unicode/char/1f453/index.htm
# ðŸ‘£ pies:               http://www.fileformat.info/info/unicode/char/1f463/index.htm
# ðŸ’ª musculo:             http://www.fileformat.info/info/unicode/char/1f4aa/index.htm
# ðŸ’¯ 100:                 http://www.fileformat.info/info/unicode/char/1f4af/index.htm
# ðŸ‘Œ mano perfecto:      http://www.fileformat.info/info/unicode/char/1f44c/index.htm

# Site settings
title: La mejor ðŸ‘Œ informaciÃ³n sobre pulseras de actividad âŒš y fitness.
email: web@pulseradeactividad.info
description: >
  Reviews y anÃ¡lisis veraces de las mejores ðŸ‘‘ pulseras de actividad, fitness, y pulsÃ³metros deportivos.
  Las opiniones mÃ¡s valiosas, consejos y comparativas. ðŸ’ª Descubre como pueden
  ayudarte a mejorar tu forma fÃ­sica .
logo: "/assets/logo.png"
logo_amp: "/assets/logo-amp.png"
logo_amp__width: 176
logo_amp__height: 60
logo_16x9: "/assets/logo-16x9.png"
logo_4x3: "/assets/logo-4x3.png"
logo_1x1: "/assets/logo-1x1.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pulseradeactividad.info" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'PulseraDeActividad.info'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"
twitter_username: jekyllrb
github_username:  jekyll

collections:
  paginas:
    output: true
    permalink: /:path.html

exclude:
  - 'README*.md'
  - 'Gemfile*'
  - 'LICENSE'
  - 'vendor'
  - '*.orig'
  - 'feed.xml'
  - 'resources'

# Google Analytics
analytics_id: "UA-158375791-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

sass:
  style: compressed
